# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-15 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_auto_20181015_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='user_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='post',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
