# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-15 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0004_auto_20181015_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='user_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='post',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
