# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-15 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0005_auto_20181015_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='insta.Detail'),
        ),
    ]
