# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-15 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0006_auto_20181015_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='insta.Detail'),
        ),
    ]
